l_english:
 SETTING_DEBUG_SAVES:0 "Number of debug saves"
 SETTING_TUTORIAL:0 "Tutorial"
 SETTING_DISABLED_HINTS:0 "Remover dicas"
 SETTING_FOCUS_ON_COMBAT:0 "Foco no combate"
 SETTING_TOOLTIP_DELAY:1 "Atraso nas dicas"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nTempo de atraso antes de exibir as dicas."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Atraso para destravar"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nTempo de atraso antes de destravar as dicas."
 SETTING_TOOLTIP_LOCK_TIME:0 "Atraso para travar"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nTempo de atraso antes de travar as dicas."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Atraso para travar abertas"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nAtraso antes de travar dicas quando já existem outras travadas aberto."
 # Audio
 SETTING_Sound_Effects:1 "Todos os efeitos sonoros"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Efeitos sonoros\n#!Volume para TODOS os efeitos sonoros."
 SETTING_Ambience:0 "Ambiente"
 SETTING_Ambience_TOOLTIP:1 "#T Volume ambiente\n#!Volume ambiente."
 SETTING_TOOLTIP_MODE:1 "Modo das dicas"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nSets the way tooltips "lock in," enabling tooltips-in-tooltips."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Mouse Tendency"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nTooltips automatically lock in place until the cursor moves away."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Action Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nPress #V Middle Mouse#! to lock and unlock tooltips."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Timer Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nTooltips are locked in place if the cursor does not move for a short while. #weak (Default setting.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Outros"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Dicas"
 SETTINGS_CATEGORY_SFX:0 "Efeitos Especiais Específicos"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Geral"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Controles do Mapa"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Jogos salvo"
 SETTINGS_CATEGORY_LANGUAGE:0 "Idioma"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Avançado – Geral"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP:0 "Avançado – Mapa"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters:0 "Avançado – Personagens"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Retratos"
 SETTINGS_CATEGORY_MULTIPLAYER:0 "Multiplayer"
 SETTINGS_CATEGORY_MAP:0 "Mapa"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Exibir doenças e machucados"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nSets whether graphic injuries and diseases will be visible on character portraits."
 SETTING_SHOW_NUDITY:0 "Mostrar nudez"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nSets whether characters can be shown nude."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE:0 "Royal Court Idle Pan"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nDetermines if the camera in the Royal Court should pan gently across your Court when idle.\n\nIf Animated Characters is turned off, this setting has no effect."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION:0 "Royal Court Smooth Transitions"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nDetermines if the camera in the Royal Court should move smoothly to a new location.\n\nIf Animated Characters is turned off, this setting has no effect."
 NEVER:0 "Nunca"
 MONTHLY:0 "Todo mês"
 HALFYEAR:0 "A cada 6 meses"
 YEARLY:0 "Todo ano"
 FIVE_YEAR:0 "A cada 5 anos"
 SETTINGS_CATEGORY_TUTORIAL:0 "Tutorial"
 SETTING_REACTIVE_TUTORIAL:1 "Mostrar Conselhos Reativos"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nDefine se o jogo deve mostrar conselhos tutoriais reagindo à forma como você joga. Útil para jogadores novos no Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Mostrar sugestões"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nConfigura se o jogo deve sugerir alguma coisa para fazer em intervalos regulares. Útil para novos jogadores de Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Redefinir conselhos reativos"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Redefinir conselhos reativos#!\nAvisos reativos já exibidos irão aparecer novamente."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Redefinir conselhos reativos"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Tem certeza que quer redefinir os conselhos reativos?"
 SETTING_ADVANCED_SHADERS:0 "Efeitos de Shader avançados"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Efeitos de Shader avançados\n#!Essa opção irá habilitar efeitos de shaders avançados.\n\nDesligar pode melhorar a performance com a perda de alguns efeito (ex. terrenos e água) ficam mais feios."
 SETTING_WINTER_PARTICLE_EFFECTS:0 "Efeitos de partículas no inverno"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nDetermina se os efeitos de partículas são exibidos ou não quando o inverno está ativo em algumas regiões do mapa.\n\nDesligar pode melhorar a performance"
 SETTING_RESET_CAMERA_ROTATION:0 "Redefinir rotação da camera"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermina se a camera deve voltar automaticamente para a posição padrão depois de girar"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS:0 "Court Scene Background Characters"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermines if the Royal Court 3D scene should display less important background characters."
 SETTING_MAP_HIGHLIGHT:0 "Destaque do cursor no Mapa"
 SETTING_MAP_HIGHLIGHT_TOOLTIP:0 "#T $SETTING_MAP_HIGHLIGHT$#!\nDetermina a intensidade dos destaques do cursor no Mapa"
 BASED_ON_ZOOM_LEVEL:0 "Dinâmico"
 ALWAYS_HIDE:0 "Sempre ocultar"
 ALWAYS_SHOW:0 "Sempre exibir"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Fronteiras Costeiras"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nEsta opção irá controlar quando as bordas de reinos costeiros devem ser exibidas.\nSe $BASED_ON_ZOOM_LEVEL$ então elas não vão aparecer no nível de zoom detalhado.\n\nPicking a $ALWAYS_SHOW$ or $ALWAYS_HIDE$ may increase performance at the cost of the coastal realm borders not hiding dynamically."
 SETTINGS_DISCARD_CHANGES:0 "Descartar alterações"
